* Added UID check for newuser and autopathing

diff --git a/scripts/usr/local/bin/shark-newuser b/scripts/usr/local/bin/shark-newuser
--- a/scripts/usr/local/bin/shark-newuser
+++ b/scripts/usr/local/bin/shark-newuser
@@ -31,11 +31,17 @@
 # shark-newuser - Create a new URTBOD tunnel server user for a Shark.
 #                 This runs on the tunnel server side.
 
+EID=`id -u`
+
+if [ "X${EID}" != "X0" ]; then
+    echo "ERROR: Please rerun as root or with sudo - Elevated privilges required"
+    exit 1
+fi
 
 NEWHOSTNAME=${1}
 
 if [ X${NEWHOSTNAME} = X ]; then
-    echo "You must specify a hostname for the new remote client"
+    echo "ERROR: You must specify a hostname for the new remote client"
     exit 1
 fi
 
@@ -46,10 +52,10 @@ while read -r PUBKEY; do
 	    echo "Public key accepted"
 	    break
 	else
-	    echo "Invalid public key format - Please re-enter"
+	    echo "WARNING: Invalid public key format - Please re-enter"
 	fi
     else
-     	echo "Invalid input - Please enter a valid SSH public key"
+     	echo "WARNING: Invalid input - Please enter a valid SSH public key"
     fi
 done
 
diff --git a/scripts/usr/local/bin/shark-statsconv b/scripts/usr/local/bin/shark-statsconv
--- a/scripts/usr/local/bin/shark-statsconv
+++ b/scripts/usr/local/bin/shark-statsconv
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright(c) 2013, Citon Computer Corporation
+# Copyright(c) 2014, Citon Computer Corporation
 # All rights reserved.
 # 
 # Redistribution and use in source and binary forms, with or without
@@ -53,16 +53,24 @@ SUFFIX=conv-$1
 # to avoid processing half complete files
 MINAGE=1000
 
+# Find tshark
+TSHARK=`which tshark`
+
+if [ "X${TSHARK}" = "X"]; then
+    echo "FATAL: tshark not found in path"
+    exit 1
+fi
+
 # The base of the tshark command to run.  Note that it will be run under nice
 # to limit interactive impact
-TSHARKCMD="/usr/local/bin/tshark -q -z conv,${TYPE} -r"
+TSHARKCMD="${TSHARK} -q -z conv,${TYPE} -r"
 
 for i in `ls ${SOURCECAPS}/`; do
         if [ `stat --printf=%Y ${SOURCECAPS}/${i}` -lt $(( `date +%s` - ${MINAGE})) ]; then
                 DEST="${DESTSTATS}/${i}-${SUFFIX}.csv"
                 if [ ! -f ${DEST} ]; then
                         echo -n "Processing ${i} to ${DEST}..."
-                        /usr/bin/nice ${TSHARKCMD} ${SOURCECAPS}/${i} > ${DEST}
+                        nice ${TSHARKCMD} ${SOURCECAPS}/${i} > ${DEST}
                         echo "Done."
                 fi
         fi
