* General bugfixes

diff --git a/scripts/etc/init.d/shark-dumpy b/scripts/etc/init.d/shark-dumpy
--- a/scripts/etc/init.d/shark-dumpy
+++ b/scripts/etc/init.d/shark-dumpy
@@ -1,4 +1,12 @@
 #!/bin/sh
+### BEGIN INIT INFO
+# Provides:          shark-dumpy
+# Required-Start:    $local_fs $network
+# Required-Stop:     $local_fs $network
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Shark Capture
+### END INIT INFO
 
 # Copyright(c) 2014, Citon Computer Corporation
 # All rights reserved.
@@ -26,6 +34,7 @@
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 # THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+
 # Continuous capture to ring buffer of multiple tcpdump files
 
 # Set to your capture interface
@@ -44,19 +53,13 @@ DUMPCAPMAXSIZE=2000000
 DUMPCAPROTTIME=1800
 
 # Set the number of capture files to maintain 
-DUMPCAPFILES=72
+DUMPCAPFILES=96
 
 # Set the log file name
 LOGFILE=/var/log/shark-dumpy.log
 
-# Manually set the paths to executables
-#DUMPCAP=/usr/local/bin/dumpcap
-DUMPCAP=/usr/bin/dumpcap
-
-IFCONFIG=/sbin/ifconfig
-
-ETHTOOL=/usr/sbin/ethtool
-
+# Set a pid file to hold our dumpcap ID
+PIDFILE=/var/run/shark-dumpy.pid
 
 ### You should not need to hack anything after this, but you are welcome
 ### to ;)
@@ -68,6 +71,35 @@ fi
 
 case "$1" in
 	start)
+
+                # Attempt to auto set the paths for utilities
+	        DUMPCAP=`which dumpcap`
+		IFCONFIG=`which ifconfig`
+		ETHTOOL=`ethtool`
+
+		if [ "X${DUMPCAP}" = "X" ]; then
+		    echo "FATAL: 'dumpcap' now found in path.  Is Wireshark installed?"
+		    exit 1
+		fi
+		
+		if [ "X${IFCONFIG}" = "X" ]; then
+		    # Assume it is under /sbin
+		    IFCONFIG="/sbin/ifconfig"
+		fi   
+		if [ ! -x ${IFCONFIG} ]; then
+		    echo "FATAL: Could not find ifconfig binary"
+		    exit 1
+		fi
+
+		if [ "X${ETHTOOL}" = "X" ]; then
+		    # Assume it is under /usr/sbin
+		    ETHTOOL="/usr/sbin/ethtool"
+		fi
+		if [ ! -x ${ETHTOOL} ]; then
+		    echo "FATAL: Could not find ethtool binary"
+		    exit 1
+		fi
+
 		# Create the capture directory if it is missing
 		if [ ! -d ${CAPDEST} ]; then
 			mkdir -p ${CAPDEST}
@@ -83,13 +115,38 @@ case "$1" in
 		# Run a continous capture - Adjust params as needed
 		echo ", dumping from ${CAPIF} to ${CAPDEST}/${HOSTNAME}-${CAPIF}"
 		${DUMPCAP} -q -b duration:${DUMPCAPROTTIME} -b files:${DUMPCAPFILES} -s 9600 -i ${CAPIF} -w ${CAPDEST}/${HOSTNAME}-${CAPIF} -f "${DUMPCAPFILT}" >> ${LOGFILE} 2>&1 &
-		
+	
+		echo $! > ${PIDFILE}
 		exit 0
 	;;
 
 	stop)
-		pkill dumpcap
+		kill `cat ${PIDFILE}`
+		rm -f ${PIDFILE}
 	;;
+        
+        status)
+
+		if [ ! -f ${PIDFILE} ]; then
+		    echo "shark-dumpy is not running"
+		    exit 1
+		fi
+
+
+	        DUMPYPID=`cat ${PIDFILE}`
+
+		# Assumes Linux ps
+	        DUMPINFO=`ps --no-headers -p ${DUMPYPID}`
+
+		if [ "X${DUMPYINFO}" != "X" ]; then
+		    echo "shark-dumpy running with PID ${DUMPYPID}"
+		    echo ${DUMPINFO}
+		    exit 0
+		else
+		    echo "shark-dumpy does not appear to be running - Removing stale PID file"
+		    rm ${PIDFILE}
+		    exit 1
+		fi
 esac
 
 exit 0
diff --git a/scripts/etc/init.d/shark-urtbod-client b/scripts/etc/init.d/shark-urtbod-client
--- a/scripts/etc/init.d/shark-urtbod-client
+++ b/scripts/etc/init.d/shark-urtbod-client
@@ -1,4 +1,12 @@
 #!/bin/sh
+### BEGIN INIT INFO
+# Provides:          shark-urtbod-client
+# Required-Start:    $local_fs $network
+# Required-Stop:     $local_fs $network
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Shark URTBOD Tunnel
+### END INIT INFO
 
 # Copyright(c) 2014, Citon Computer Corporation
 # All rights reserved.
@@ -31,11 +39,31 @@
 # a modified /root/.ssh/config file to call socat when connecting
 # to your server
 
-# Set the FQDN of the server to connect to - Set in /etc/hosts if needed
-URTBODSERVER=__URTBODSERVER__
+# Set the FQDN of the server to connect to using the shark-urtbodserver config
+# file
+if [ -f /etc/shark-urtbodserver ]; then
+    URTBODSERVER=`cat /etc/shark-urtbodserver`
+    if [ "X${URTBODSERVER}" = "Xsetme" ]; then
+	echo "$0 FATAL: You must set the fully qualified name or IP for your URTBOD tunnel server in /etc/shark-urtbodserver."
+	exit 1
+    fi
+else
+    echo "$0 FATAL: The URTBOD config file /etc/shark-urtbodserver is missing.  You must set the fully qualified name or IP for your URTBOD tunnel server in /etc/shark-urtbodserver."
+    exit 1
+fi
 
 # Set the three digit unit number for this system - IT MUST BE UNIQUE!
-UNIT=__SHARKNUMBER__
+if [ -f /etc/shark-unit ]; then
+    UNIT=`cat /etc/shark-unit`
+    if [ "X${UNIT}" = "Xxxx" ]; then
+	echo "$0 FATAL: You must set a 3 digit Shark unit number in /etc/shark-unit and it must be unique to the URTBOD server you are connecting to"
+	exit 1
+    fi
+else
+    echo "$0 FATAL: The URTBOD config file /etc/shark-unit is missing. You must set a 3 digit Shark unit number in /etc/shark-unit and it must be unique to the URTBOD server you are connecting to." 
+    exit 1
+fi
+
 
 # Set a unique port to forward from the remote server.  THIS MUST
 # BE DIFFERENT FOR EACH CLIENT!
@@ -69,6 +97,12 @@ case "$1" in
 	stop)
 		rm /var/run/shark-urtbod-client
 		pkill autossh
+	;;
+
+        status)
+	        if [ -e /var/run/shark-urtbod-client ]; then
+		    echo "shark-urtbod-client pid detected - Enabled"
+		fi
 	;;
 esac
 
